name: Cypress Tests

on: 
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Fix Cypress Permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Run Send Report
        run: node sendReport.js
        
